<?php
/**
 * Created by PhpStorm.
 * User: miaonot
 * Date: 2017/6/5
 * Time: 下午11:54
 */
?>
<html>
    <head>
        <meta charset="UTF-8">
        <title>编辑器</title>
        <link href="../public/css/materialize.css" rel="stylesheet" type="text/css"/>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script src="../public/js/jquery-2.1.1.min.js" type="text/javascript"></script>
        <script src="../public/js/materialize.js" type="text/javascript"></script>
    </head>
    <body>
        <nav class="light-blue lighten-1" role="navigation">
            <div class="nav-wrapper container">
                <!-- TODO: href and Logo need to be changed -->
                <a href="../public/index" class="brand-logo">Logo</a>
                <ul class="right hide-on-med-and-down">
                    <li>
                        <a href="../public/logout">登出</a>
                    </li>
                </ul>
                <ul id="nav-mobile" class="side-nav" style="transform: translateX(-100%);">
                    <li>
                        <a href="../public/logout">登出</a>
                    </li>
                </ul>
                <a href="#" data-activates="nav-mobile" class="button-collapse">
                    <i class="material-icons">menu</i>
                </a>
            </div>
        </nav>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row">
            <div class="col m2"></div>
            <div class="col m8">
                <div class="card hoverable">
                    <div class="card-content" id="editControls">
                        <a class="waves-effect waves-teal btn-flat" id="submit" data-role='undo'">
                            <span class="teal-text text-lighten-2">撤销</span>
                        </a>
                        <a class="waves-effect waves-teal btn-flat" id="submit" data-role='redo'">
                            <span class="teal-text text-lighten-2">重做</span>
                        </a>
                        <a class="waves-effect waves-teal btn-flat" id="submit" data-role='bold'">
                            <span class="teal-text text-lighten-2">加粗</span>
                        </a>
                        <a class="waves-effect waves-teal btn-flat" id="submit" data-role='h1'">
                            <span class="teal-text text-lighten-2">h1</span>
                        </a>
                        <a class="waves-effect waves-teal btn-flat" id="submit" data-role='p'">
                            <span class="teal-text text-lighten-2">p</span>
                        </a>
                        <div class="row">
                            <form class="col m12">
                                <div class="row">
                                    <div class="input-field col s12">
                                        <div id="textarea" class="materialize-textarea" contenteditable>单击编辑</div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col m2"></div>
        </div>
        <script>
            (function($){
                $(function(){

                    $('.button-collapse').sideNav();

                }); // end of document ready
            })(jQuery); // end of jQuery name space

            $(function() {
                $('#editControls').find('a').click(function(e) {
                    switch($(this).data('role')) {
                        case 'h1':
                        case 'p':
                            document.execCommand('formatBlock', false, '<' + $(this).data('role') + '>');
                            break;
                        default:
                            document.execCommand($(this).data('role'), false, null);
                            break;
                    }
                })
            });

            window.onload = function () {
                if (localStorage.getItem('doc') != null) {
                    document.getElementById('textarea').innerHTML = localStorage.getItem('doc');
                }
            }

            lock = false;

            document.addEventListener("DOMSubtreeModified", function () {
                var editor = document.getElementById("textarea");
                if (localStorage.getItem('doc') !== editor.innerHTML) {
                    if (!lock) {
                        lock = true;
                        setTimeout(function () {
                            localStorage.setItem('doc', editor.innerHTML);
                            lock = false;
                        }, 10000);
                    }
                }
            });
        </script>
    </body>
</html>