<?php
/**
 * Created by PhpStorm.
 * User: miaonot
 * Date: 2017/5/10
 * Time: 下午1:38
 */
?>
<html>
    <head>
        <meta charset="UTF-8">
        <title>注册</title>
        <link href="../public/css/materialize.css" rel="stylesheet" type="text/css"/>
        <script src="../public/js/jquery-2.1.1.min.js" type="text/javascript"></script>
        <script src="../public/js/materialize.js" type="text/javascript"></script>
    </head>
    <body>
        <div class="row">
            <div class="col m3"></div>
            <div class="col s12 m6">
                <div class="card hoverable">
                    <div class="card-content">
                        <div class="row">
                            <form class="col s12">
                                <div class="row">
                                    <div class="input-field col s6">
                                        <input id="user_name" type="text" class="validate">
                                        <label for="user_name">用户名</label>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="card-action">

                    </div>
                </div>
            </div>
            <div class="col m3"></div>
        </div>
    </body>
</html>
