<?php
/**
 * Created by PhpStorm.
 * User: miaonot
 * Date: 2017/5/17
 * Time: 下午7:53
 */
?>
<html>
    <head>
        <meta charset="UTF-8">
        <title>登陆</title>
        <link href="../public/css/materialize.css" rel="stylesheet" type="text/css"/>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script src="../public/js/jquery-2.1.1.min.js" type="text/javascript"></script>
        <script src="../public/js/materialize.js" type="text/javascript"></script>
    </head>
    <body>
        <nav class="light-blue lighten-1" role="navigation">
            <div class="nav-wrapper container">
                <!-- TODO: href and Logo need to be changed -->
                <a href="../public/index" class="brand-logo">Logo</a>
                <ul class="right hide-on-med-and-down">
                    <li>
                        <a href="../public/join">注册</a>
                    </li>
                </ul>
                <ul id="nav-mobile" class="side-nav" style="transform: translateX(-100%);">
                    <li>
                        <a href="../public/join">注册</a>
                    </li>
                </ul>
                <a href="#" data-activates="nav-mobile" class="button-collapse">
                    <i class="material-icons">menu</i>
                </a>
            </div>
        </nav>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row">
            <div class="col m3"></div>
            <div class="col s12 m6">
                <div class="card hoverable">
                    <div class="card-content">
                        <div style="width: 100px; height: 100px; border-radius: 50%; overflow:hidden; align-self: center">
                            <!-- TODO: Logo needs to be changed -->
                            <img src="../public/pic/Logo.jpg"/>
                        </div>
                        <form id="form">
                            <div class="row">
                                <div class="input-field col s12">
                                    <!-- TODO: check username -->
                                    <input id="user_name" type="text" class="validate" onblur="">
                                    <label id="user_name_label" for="user_name">用户名</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12">
                                    <input id="password" type="password" class="validate">
                                    <label id="password_label" for="password">密码</label>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="card-action">
                        <a class="waves-effect waves-teal btn-flat" id="submit" onclick="login()">
                            <span class="teal-text text-lighten-2">登陆</span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col m3"></div>
        </div>
        <div class="drag-target" data-sidenav="nav-mobile" style="touch-action: pan-y; left: 0px;"></div>
        <script type="text/javascript">
            <!-- TODO: -->
            function login() {
                var userName = document.getElementById("user_name");
                var password = document.getElementById("password");
                var data = "username=" + userName.value + "&password=" + password.value;
                var xmlhttp = new XMLHttpRequest();
                xmlhttp.onreadystatechange = function() {
                    if (xmlhttp.readyState === 4 && xmlhttp.status === 200) {
                        if (xmlhttp.responseText === "error") {
                            Materialize.toast("用户名已存在", 3000);
                        } else {
                            window.location.href = "index";
                        }
                    }
                    else if (xmlhttp.readyState === 4 && xmlhttp.status !== 200) {
                        Materialize.toast("网络错误，请重试", 3000);
                    }
                };
                xmlhttp.open("POST", "../public/join", true);
                xmlhttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
                xmlhttp.send(data);
            }
            (function($){
                $(function(){

                    $('.button-collapse').sideNav();

                }); // end of document ready
            })(jQuery); // end of jQuery name space
        </script>
    </body>
</html>
